simplify helpers

diff --git a/bin/install-if-newer b/bin/install-if-newer
--- a/bin/install-if-newer
+++ b/bin/install-if-newer
@@ -1,32 +1,19 @@
 #!/bin/bash
 
-#!/bin/bash
-
-set -e
+[[ -z $ROOT ]] && echo "ROOT: missing" && exit 1
+[[ $# != 2 ]] && echo "Usage: $0 <src> <cmd>" && exit 1
 
 src=$1
 cmd=$2
 
-if [[ -z $src || -z $cmd ]]; then
-    echo "Usage: $0 <src> <cmd>"
-    exit 1
-fi
-
 packages=$ROOT/packages/$src
 packages_marker=$ROOT/state/packages-$src
 
-if [[ ! -f $packages ]]; then
-    echo "No packages to install, missing: $packages"
-    exit 0
-fi
-
-if [[ $packages -ot $packages_marker ]]; then
-    exit 0
-fi
+[[ ! -f $packages ]] && echo "No packages to install, missing: $packages" && exit 0
+[[ $packages -ot $packages_marker ]] && exit 0
 
 packages="$(grep -v '^#' $packages | tr '\n' ' ')"
 
 echo "$src: installing: $packages"
 eval "$cmd $packages"
-mkdir -p $(dirname $packages_marker)
 touch $packages_marker
diff --git a/bin/once b/bin/once
--- a/bin/once
+++ b/bin/once
@@ -1,15 +1,13 @@
 #!/bin/bash
 # run a command once only if the state file doesn't exist
 
+[[ -z $ROOT ]] && echo "ROOT: missing" && exit 1
+[[ $# != 2 ]] && echo "Usage: $0 <state-file> <command>" && exit 1
+
 state=$1
 cmd=$2
 
-if [[ -z $state || -z $cmd ]]; then
-    echo "Usage: $0 <state-file> <command>"
-    exit 1
-fi
-
-marker=$ROOT/state/$1
+marker=$ROOT/state/$state
 
 if [[ ! -f $marker ]]; then
     echo "$state: running once"
